name: CI

on:
  push:
    # branches:
    #   - main
    tags:
      - '*'

env:
  FIRMWARE_BASE: repository # use something like repository/firmware in case this is a repo with other things like hardware

jobs:
  checkout:
    runs-on: ubuntu-latest
    name: Checkout
    steps:
      - name: Cache repository
        uses: actions/cache@v4
        id: cache-repository
        with:
          path: repository
          key: ${{ runner.os }}-repository-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-repository-

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: repository
          submodules: recursive

  install-idf:
    runs-on: ubuntu-latest
    name: Install esp-idf
    needs:
      - checkout
    steps:
      - name: Cache repository
        uses: actions/cache@v4
        id: cache-repository
        with:
          path: repository
          key: ${{ runner.os }}-repository-${{ github.sha }}

      - name: Verify that "Cache repostory" had a hit
        if: ${{ steps.cache-repository.outputs.cache-hit != 'true' }}
        run: exit 1

      - name: Get esp-idf release name
        id: get-esp-idf-release
        run: echo "tag_name=$(git -C $FIRMWARE_BASE/esp-idf rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Cache .espressif
        id: cache-espressif
        uses: actions/cache@v4
        with:
          path: ~/.espressif
          key: ${{ runner.os }}-espressif-${{ steps.get-esp-idf-release.outputs.tag_name }}

      - name: Install .espressif dependencies
        if: ${{ steps.cache-espressif.outputs.cache-hit != 'true' }}
        run: $FIRMWARE_BASE/esp-idf/install.sh

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [default, diodes]
    name: ${{ matrix.node }}
    needs:
      - checkout
      - install-idf
    steps:
      - name: Cache repository
        uses: actions/cache@v4
        id: cache-repository
        with:
          path: repository
          key: ${{ runner.os }}-repository-${{ github.sha }}

      - name: Verify that "Cache repostory" had a hit
        if: ${{ steps.cache-repository.outputs.cache-hit != 'true' }}
        run: exit 1

      - name: Get esp-idf release name
        id: get-esp-idf-release
        run: echo "tag_name=$(git -C $FIRMWARE_BASE/esp-idf describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Cache .espressif
        id: cache-espressif
        uses: actions/cache@v4
        with:
          path: ~/.espressif
          key: ${{ runner.os }}-espressif-${{ steps.get-esp-idf-release.outputs.tag_name }}

      - name: Verify that "Cache .espressif" had a hit
        if: ${{ steps.cache-espressif.outputs.cache-hit != 'true' }}
        run: |
          echo "Cache .espressif did not hit? Did the prepare step run successfully?"
          exit 1

      - name: Build firmware
        id: build-firmware
        run: |
          cd $FIRMWARE_BASE
          ./esp-idf/install.sh
          . export.sh
          ./switchconf.sh ${{ matrix.node }}
          idf.py build 
          FIRMWARE_PATH=$(find build_${{ matrix.node }}/ -maxdepth 1 -name '*.bin' -type f)
          FIRMWARE_BASENAME=$(basename $FIRMWARE_PATH)
          FIRMWARE_NAME=${FIRMWARE_BASENAME%.bin}
          FIRMWARE_FOLDER=${FIRMWARE_PATH%$FIRMWARE_BASENAME}
          NEW_FIRMWARE_LOCATION=${FIRMWARE_FOLDER}${FIRMWARE_NAME}_${{ matrix.node }}.bin
          
          mv $FIRMWARE_PATH $NEW_FIRMWARE_LOCATION
          
          echo "FIRMWARE_LOCATION=$NEW_FIRMWARE_LOCATION" >> $GITHUB_OUTPUT

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.node }}
          path: repository/${{ steps.build-firmware.outputs.FIRMWARE_LOCATION }}

  create-release:
    runs-on: ubuntu-latest
    name: Create release
    needs:
      - build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download firmware binaries
        uses: actions/download-artifact@v4
        with:
          path: ${{ github.workspace }}/firmware
          pattern: firmware-*
          merge-multiple: true

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/firmware/*
          tag_name: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Firmware binaries for ${{ github.ref }}
          draft: true
          prerelease: false
